version: '3'

services:
   adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
   db:
    image: postgres:15.2-alpine3.17
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=exampledb
   
   example-application:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: "new,postgresql" 
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exampledb
    ports:
      - "8080:8080"
    depends_on:
      - db