spring:
   redis:
      host: localhost
      port: 6379
server:
   servlet:
      session:
         timeout: 15m
         cookie:
            http-only: true # if true then browser script won't be able to access the cookie
            secure: false # if true then the cookie will be sent only over HTTPS connection
