version: '3'
# https://hellokoding.com/docker-compose-with-spring-boot-nginx/
services:
  haproxy:
   image: haproxy:latest
   volumes:
       - ./haproxy:/haproxy-override
       - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
   ports:
       - "80:80"
       - "70:70" # haproxy admin console, login with user:pass
   depends_on:
   - example1
   - example2  
  example1:
    build: .
    depends_on:
    - redis
  example2:
    build: .
    depends_on:
    - redis  
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis
  redis:
   image: redis:latest
   ports:
    - "6379:6379"


