spring:
  datasource:
    password: ''
    url: jdbc:h2:mem:registration_02;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
     enabled: true
     path: /h2
         
  main:
    allow-bean-definition-overriding: true
    
  thymeleaf:
    cache: false