version: '3'
# https://hellokoding.com/docker-compose-with-spring-boot-nginx/
services:
  haproxy:
   image: haproxy:latest
   volumes:
       - ./haproxy:/haproxy-override
       - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
   ports:
       - "80:80"
       - "70:70" # haproxy admin console, login with user:pass
   depends_on:
   - example1
   - example2  
  example1:
    build: .
  example2:
    build: .  


