version: '3'
# https://hellokoding.com/docker-compose-with-spring-boot-nginx/
services:
  web:
   image: nginx:latest
   ports:
      - "80:80"
      - "443:443"
   volumes:
   - ./nginx:/etc/nginx/conf.d
   depends_on:
   - example  
  example:
    build: .
    deploy:
      mode: replicated
      replicas: 2

